branch-defaults:
  default:
    environment: best-vulpy-172rb5x5-env
environment-defaults:
  best-vulpy-172rb5x5-env:
    branch: null
    repository: null
global:
  application_name: best-vulpy-172rb5x5
  default_ec2_keyname: null
  default_platform: Python 3.9 running on 64bit Amazon Linux 2023
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
